#!/usr/bin/env bash

DIRNAME=${0%/*}
TAP=1 node ./$DIRNAME/one-subtest-failures.js > ./$DIRNAME/one-subtest-failures.tap
TAP=1 node ./$DIRNAME/subtests-failures.js > ./$DIRNAME/subtests-failures.tap
TAP=1 node ./$DIRNAME/one-subtest.js > ./$DIRNAME/one-subtest.tap
TAP=1 node ./$DIRNAME/subtests.js > ./$DIRNAME/subtests.tap
